compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.12.0.cjs

npmPublishRegistry: https://registry.npmjs.org

npmAuthToken: ${NPM_TOKEN-""}

npmPublishAccess: public
