name: "\U0001F41B Bug Report"
description: Report a bug in LangGraph.js. To report a security issue, please instead use the security option below. For questions, please use the GitHub Discussions.
labels: ["02 Bug Report"]
body:
  - type: markdown
    attributes:
      value: >
        Thank you for taking the time to file a bug report. 

        Use this to report bugs in LangGraph.js. 

        If you're not certain that your issue is due to a bug in LangGraph.js, please use [GitHub Discussions](https://github.com/langchain-ai/langgraphjs/discussions)
        to ask for help with your issue.

        Relevant links to check before filing a bug report to see if your issue has already been reported, fixed or
        if there's another way to solve your problem:

        [LangGraph.js documentation with the integrated search](https://langchain-ai.github.io/langgraphjs/),
        [API Reference](https://langchain-ai.github.io/langgraphjs/reference/),
        [LangChain Forum](https://forum.langchain.com/)
        [GitHub search](https://github.com/langchain-ai/langgraphjs),
        [LangGraph.js Github Discussions](https://github.com/langchain-ai/langgraphjs/discussions),
        [LangGraph.js Github Issues](https://github.com/langchain-ai/langgraphjs/issues?q=is%3Aissue),
  - type: checkboxes
    id: checks
    attributes:
      label: Checked other resources
      description: Please confirm and check all the following options.
      options:
        - label: I added a very descriptive title to this issue.
          required: true
        - label: I searched the LangGraph.js documentation with the integrated search.
          required: true
        - label: I used the GitHub search to find a similar question and didn't find it.
          required: true
        - label: I am sure that this is a bug in LangGraph.js rather than my code.
          required: true
        - label: The bug is not resolved by updating to the latest stable version of LangGraph (or the specific integration package).
          required: true
  - type: textarea
    id: reproduction
    validations:
      required: true
    attributes:
      label: Example Code
      description: |
        Please add a self-contained, [minimal, reproducible, example](https://stackoverflow.com/help/minimal-reproducible-example) with your use case.

        If a maintainer can copy it, run it, and see it right away, there's a much higher chance that you'll be able to get help.

        **Important!** 

        * Use code tags (e.g., ```typescript ... ```) to correctly [format your code](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#syntax-highlighting).
        * INCLUDE the language label (e.g. `typescript`) after the first three backticks to enable syntax highlighting. (e.g., ```typescript rather than ```).
        * Reduce your code to the minimum required to reproduce the issue if possible. This makes it much easier for others to help you.
        * Avoid screenshots when possible, as they are hard to read and (more importantly) don't allow others to copy-and-paste your code.

      placeholder: |
        The following code: 

        ```typescript
        import { StateGraph, Annotation } from "@langchain/langgraph";

        const graph = new StateGraph(
          Annotation.Root({ messages: Annotation<string[]> }),
        )
          .addNode("node", (state) => {
            throw new Error("Invalid code");
            return { messages: [...state.messages, "Hello, world!"] };
          })
          .compile();

        console.log(await graph.invoke({ messages: ["Hello, world!"] }));
        ```
  - type: textarea
    id: error
    validations:
      required: false
    attributes:
      label: Error Message and Stack Trace (if applicable)
      description: |
        If you are reporting an error, please include the full error message and stack trace.
      placeholder: |
        Error + full stack trace
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        What is the problem, question, or error?

        Write a short description telling what you are doing, what you expect to happen, and what is currently happening.
      placeholder: |
        * I'm trying to use the `@langchain/langgraph` library to do X.
        * I expect to see Y.
        * Instead, it does Z.
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: |
        Please share your system info with us. 

        Run `npx @langchain/langgraph-cli@latest sysinfo` and paste the output here.

        Alternatively, you can also paste the following:

        - Package Info (`npm ls` / `yarn info` / `pnpm list`)
        - Platform (Windows / Linux / Mac)
        - Node version
        - Package Manager (Yarn / NPM / PNPM / Bun) and version of the package manager
      placeholder: |
        Run `npx @langchain/langgraph-cli@latest sysinfo` and paste the output here.

        Alternatively, you can also paste the following:

        - Package Info (`npm ls` / `yarn info` / `pnpm list`)
        - Platform (Windows / Linux / Mac)
        - Node version
        - Package Manager (Yarn / NPM / PNPM / Bun) and version of the package manager
    validations:
      required: true
