blank_issues_enabled: false
version: 2.1
contact_links:
  - name: 🤔 Question or Problem
    about: Ask a question or ask about a problem in GitHub Discussions.
    url: https://www.github.com/langchain-ai/langgraphjs/discussions/categories/q-a
  - name: Feature Request
    url: https://www.github.com/langchain-ai/langgraphjs/discussions/categories/ideas
    about: Suggest a feature or an idea
  - name: Show and tell
    about: Show what you built with LangGraph
    url: https://www.github.com/langchain-ai/langgraphjs/discussions/categories/show-and-tell
  - name: LangChain Forum
    url:  https://forum.langchain.com/
    about: General community discussions and support