name: 🔒 Privileged
description: You are a LangGraph.js maintainer, or was asked directly by a maintainer to create an issue here. If not, check the other options.
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in LangGraph.js! 🚀
        
        If you are not a LangGraph.js maintainer or were not asked directly by a maintainer to create an issue, then please start the conversation in [LangChain Forum](https://forum.langchain.com) instead.
        
        You are a LangGraph.js maintainer if you maintain any of the packages inside of the LangGraph.js repository 
        or are a regular contributor to LangGraph.js with previous merged merged pull requests.
  - type: checkboxes
    id: privileged
    attributes:
      label: Privileged issue
      description: Confirm that you are allowed to create an issue here.
      options:
        - label: I am a LangGraph.js maintainer, or was asked directly by a LangGraph.js maintainer to create an issue here.
          required: true
  - type: textarea
    id: content
    attributes:
      label: Issue Content
      description: Add the content of the issue here.
